config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'pages#index'
  
  resources :pages
  post 'pages/search' => 'pages#search', as: :article_search
  
  resources :articles
  

end

app/models/ad.rb
class Ad < ActiveRecord::Base
end

app/models/article.rb
class Article < ActiveRecord::Base
  
  has_many :comments, dependent: :destroy
  belongs_to :user
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  
end

app/models/payment.rb
class Payment < ActiveRecord::Base
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
end

app/models/trip.rb
class Trip < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
         
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  
  def show
    pp = params[:id]
    
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def index
    @name = "dodol Jawa"
  end
  
  def search
    p "----- #{params[:q]}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>Magazine - Brave</title>
	<!-- Description, Keywords and Author -->
	<meta name="description" content="Your description">
	<meta name="keywords" content="Your,Keywords">
	<meta name="author" content="ResponsiveWebInc">
	
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
	<!-- Styles -->
	<!-- Bootstrap CSS -->
	<link href="/assets/bootstrap.min.css" rel="stylesheet">
	<link href="/assets/bootstrap.icon-large.min.css" rel="stylesheet">
	<!-- Font awesome CSS -->
	<link href="/assets/font-awesome.min.css" rel="stylesheet">
	<!-- Magnific Popup -->
	<link href="/assets/magnific-popup.css" rel="stylesheet">
	<!-- Owl carousel -->
	<link href="/assets/owl.carousel.css" rel="stylesheet">
	
	<!-- CSS for this page -->
	
	<!-- CSS testing -->
	
	<!-- Base style -->
	<link href="/assets/style.css" rel="stylesheet">
	<!-- Skin CSS -->
	<link href="/assets/skin-green.css" rel="stylesheet" id="color_theme">
	
	<!-- Custom CSS. Type your CSS code in custom.css file -->
	<link href="/assets/custom.css" rel="stylesheet">
	
	<!-- Favicon -->
	<link rel="shortcut icon" href="#">
	
	

  <!-- Javascript for this page -->

  <!-- Custom JS. Type your JS code in custom.js file -->
  <script src="/assets/application.js"></script>
</head>



<body>
  <%= render "layouts/header/default_header" %>

  <%= yield %>

  <%= render "layouts/footer/default_footer" %>
</body>
</html>

app/views/layouts/footer/_default_footer.erb
	<footer>
		<!-- Container -->
		<div class="container">
			<!-- Footer Content -->
				
				<ul class="list-inline pull-left" style="width: 50%;">
					<div class="brand-bg" style="display: inline-block;">
						<!-- Social Media Icons -->
						<a href="#" class="facebook"><i class="fa fa-facebook circle-3"></i></a>
						<a href="#" class="twitter"><i class="fa fa-twitter circle-3"></i></a>
						<a href="#" class="google-plus"><i class="fa fa-google-plus circle-3"></i></a>
						<a href="#" class="linkedin"><i class="fa fa-linkedin circle-3"></i></a>
						<a href="#" class="pinterest"><i class="fa fa-pinterest circle-3"></i></a>
					</div>
          
          <%#= render "pages/widget/searchbox.html"%>
				</ul>
				<!-- Paragraph -->
				<p class="pull-right">Copyright &copy; 2015 - <a href="#">Storyveller</a></p>
				<!-- Clearfix -->
				<div class="clearfix"></div>
		</div>
	</footer>
	
	<!-- Footer Ends -->

</div>

<!-- Outer Ends -->		

<!-- Scroll to top -->
<!-- ><span class="totop"><a href="#"><i class="fa fa-angle-up bg-color"></i></a></span> -->

app/views/layouts/header/_default_header.erb
<!-- Outer Starts -->
<div class="outer">
	
	<!-- Header One Starts -->
	<div class="header-1">
		
		<div class="navi">	
			<div class="container">
			  <div class="row">
			    <div class="col-md-7 logo">
			      <%= 
			        link_to root_path do 
			          image_tag "img/logo/logo-storyveller.png" 
		          end
			      %>
			    </div>
			    <div class="col-md-4">
			      <span class="brand"> * Travelling journal for travellers</span>
			    </div>
			  </div>
			  
			  <div class="row padding-top-5">
			    <div class="col-md-8">
			      
			      <%= render "layouts/nav/mega_menu"%>
            
			    </div>
			    <div class="col-md-4">
			      <div class="search pull-right">



              <%= form_tag(article_search_path, id: "custom-search-form", class: "form-search form-horizontal" ) do %>  
                  <div class="input-append span12">
                      <input type="text" class="search-query mac-style" name="q" placeholder="Search">
                      <button type="submit" class="btn"><i class="icon-search"></i></button>
                  </div>
              <% end %>

            </div>
			    </div>
			    
			  </div>
			</div>
		</div>

		<div class="header-search">

		</div>
		
		<!-- Navigation ends -->
		
	</div>

	<!-- Header one ends -->

app/views/layouts/nav/_mega_menu.erb
<nav class="navbar">
  <div class="navbar-header">
		<button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".js-navbar-collapse">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
	</div>
	
	
	<div class="collapse navbar-collapse js-navbar-collapse">
		<ul class="nav navbar-nav">
			<li class="dropdown mega-dropdown">
				<a href="index.html#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bars"></i>&nbsp;&nbsp;BEGIN YOUR EXPLORATION! <span class="glyphicon glyphicon-chevron-down pull-right"></span></a>

				<ul class="dropdown-menu mega-dropdown-menu row" style="border: 1px solid #ABABAB;background-color: #000; width: 120%;">
					<li class="col-sm-3">
						<ul>
							<li class="dropdown-header">New in Stores</li>                            
                <div id="myCarousel" class="carousel slide" data-ride="carousel">
                  <div class="carousel-inner">
                    <div class="item active">
                        <a href="#"><img src="http://placehold.it/254x150/3498db/f5f5f5/&text=New+Collection" class="img-responsive" alt="product 1"></a>
                        <h4><small>Summer dress floral prints</small></h4>                                        
                        <button class="btn btn-primary" type="button">49,99 €</button> <button href="#" class="btn btn-default" type="button"><span class="glyphicon glyphicon-heart"></span> Add to Wishlist</button>       
                    </div><!-- End Item -->
                    <div class="item">
                        <a href="#"><img src="http://placehold.it/254x150/ef5e55/f5f5f5/&text=New+Collection" class="img-responsive" alt="product 2"></a>
                        <h4><small>Gold sandals with shiny touch</small></h4>                                        
                        <button class="btn btn-primary" type="button">9,99 €</button> <button href="#" class="btn btn-default" type="button"><span class="glyphicon glyphicon-heart"></span> Add to Wishlist</button>        
                    </div><!-- End Item -->
                    <div class="item">
                        <a href="#"><img src="http://placehold.it/254x150/2ecc71/f5f5f5/&text=New+Collection" class="img-responsive" alt="product 3"></a>
                        <h4><small>Denin jacket stamped</small></h4>                                        
                        <button class="btn btn-primary" type="button">49,99 €</button> <button href="#" class="btn btn-default" type="button"><span class="glyphicon glyphicon-heart"></span> Add to Wishlist</button>      
                    </div><!-- End Item -->                                
                  </div><!-- End Carousel Inner -->
                </div><!-- /.carousel -->
                <li class="divider"></li>
                <li><a href="#">View all Collection <span class="glyphicon glyphicon-chevron-right pull-right"></span></a></li>
						</ul>
					</li>
					<li class="col-sm-3">
						<ul>
							<li class="dropdown-header">Dresses</li>
							<li><a href="#">Unique Features</a></li>
							<li><a href="#">Image Responsive</a></li>
							<li><a href="#">Auto Carousel</a></li>
							<li><a href="#">Newsletter Form</a></li>
							<li><a href="#">Four columns</a></li>
							<li class="divider"></li>
							<li class="dropdown-header">Tops</li>
							<li><a href="#">Good Typography</a></li>
						</ul>
					</li>
					<li class="col-sm-3">
						<ul>
							<li class="dropdown-header">Jackets</li>
							<li><a href="#">Easy to customize</a></li>
							<li><a href="#">Glyphicons</a></li>
							<li><a href="#">Pull Right Elements</a></li>
							<li class="divider"></li>
							<li class="dropdown-header">Pants</li>
							<li><a href="#">Coloured Headers</a></li>
							<li><a href="#">Primary Buttons & Default</a></li>
							<li><a href="#">Calls to action</a></li>
						</ul>
					</li>
					<li class="col-sm-3">
						<ul>
							<li class="dropdown-header">Accessories</li>
							<li><a href="#">Default Navbar</a></li>
							<li><a href="#">Lovely Fonts</a></li>
							<li><a href="#">Responsive Dropdown </a></li>							
							<li class="divider"></li>
              <li class="dropdown-header">Newsletter</li>
              <form class="form" role="form">
                <div class="form-group">
                  <label class="sr-only" for="email">Email address</label>
                  <input type="email" class="form-control" id="email" placeholder="Enter email">                                                              
                </div>
                <button type="submit" class="btn btn-primary btn-block">Sign in</button>
              </form>                                                       
						</ul>
					</li>
				</ul>

			</li>
		</ul>
		

	</div><!-- /.nav-collapse -->
	
	
	
	
	
</nav>